Under certeain conditions, even when shapes differ, we can still perform elementwise binary operations by invoking the "Broadcasting Mechanism".

1- Expand one or both arrays by copying elements along axes with length 1 so that after this transformation, the two tensors have the same shape.

2- Perform an elementwise operation on the resulting arrays.

In [3]:
import torch 
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))


In [4]:
print(a)
print(b)

tensor([[0],
        [1],
        [2]])
tensor([[0, 1]])


In [5]:
print(a + b)  # Broadcasting addition

tensor([[0, 1],
        [1, 2],
        [2, 3]])
